services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: speech-app:latest
    container_name: speech-api
    ports:
      - "8001"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    restart: unless-stopped
    # Para acessar dispositivos de áudio, se necessário
    # devices:
    #   - "/dev/snd:/dev/snd"
